package mainFrame.otherFrames;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mainFrame.Contacto;

public class AgregarGUI extends javax.swing.JDialog {

    private ArrayList<Contacto> listaContactos;
    private DefaultTableModel tableModel;

    public AgregarGUI(java.awt.Frame parent, boolean modal,
            ArrayList<Contacto> listaContactos, DefaultTableModel tableModel) {
        super(parent, modal);
        this.listaContactos = listaContactos;
        this.tableModel = tableModel;

        initComponents();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        favCheck = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Agregar nuevo contacto");
        setResizable(false);

        jLabel1.setText("Nombre:");

        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFieldFocusLost(evt);
            }
        });
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Teléfono:");

        telField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        telField.setForeground(java.awt.Color.lightGray);
        telField.setText("Ingrese un número de tel");
        telField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telFieldFocusLost(evt);
            }
        });
        telField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        emailField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailField.setForeground(java.awt.Color.lightGray);
        emailField.setText("Ingrese un email");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        favCheck.setText("Favorito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(telField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(nombreField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        okButton.setText("Agregar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton, java.awt.BorderLayout.WEST);

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        verificarFields();

        String contactName = nombreField.getText().trim();
        String contactTel = telField.getText().trim();
        String contactEmail = emailField.getText().trim();
        boolean favValue = favCheck.isSelected();

        if (!nombreField.getText().trim().isEmpty()) {

            Contacto newContact = new Contacto(contactName, contactTel, contactEmail);
            newContact.setFav(favValue);
            listaContactos.add(newContact);
            if (favValue) {
                tableModel.addRow(new Object[]{"★", newContact.getNombre(),
                    newContact.getTel(), newContact.getEmail()});
            } else {
                tableModel.addRow(new Object[]{"", newContact.getNombre(),
                    newContact.getTel(), newContact.getEmail()});
            }
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del contacto",
                    " Advertencia", JOptionPane.WARNING_MESSAGE);
            nombreField.requestFocus();
            nombreField.setFont(new Font("Tahoma", Font.PLAIN, 11));
            nombreField.setForeground(Color.BLACK);
        }


    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        dispose();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost

        if (emailField.getText().isEmpty()) {
            emailField.setFont(new Font("Tahoma", Font.ITALIC, 11));
            emailField.setForeground(Color.LIGHT_GRAY);
            emailField.setText("Ingrese un email");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void telFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telFieldFocusLost

        if (telField.getText().isEmpty()) {
            telField.setFont(new Font("Tahoma", Font.ITALIC, 11));
            telField.setForeground(Color.LIGHT_GRAY);
            telField.setText("Ingrese un número de tel");
        }

    }//GEN-LAST:event_telFieldFocusLost

    private void nombreFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusLost

        if (nombreField.getText().isEmpty()) {
            nombreField.setFont(new Font("Tahoma", Font.ITALIC, 11));
            nombreField.setForeground(Color.LIGHT_GRAY);
            nombreField.setText("Ingrese un nombre");
        }

    }//GEN-LAST:event_nombreFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained

        if (!emailField.getText().isEmpty()
                && emailField.getForeground().equals(Color.LIGHT_GRAY)) {
            emailField.setText("");
            emailField.setFont(new Font("Tahoma", Font.PLAIN, 11));
            emailField.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_emailFieldFocusGained

    private void telFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telFieldFocusGained

        if (!telField.getText().isEmpty()
                && telField.getForeground().equals(Color.LIGHT_GRAY)) {
            telField.setText("");
            telField.setFont(new Font("Tahoma", Font.PLAIN, 11));
            telField.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_telFieldFocusGained

    private void nombreFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusGained

        if (!nombreField.getText().isEmpty()
                && nombreField.getForeground().equals(Color.LIGHT_GRAY)) {
            nombreField.setText("");
            nombreField.setFont(new Font("Tahoma", Font.PLAIN, 11));
            nombreField.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_nombreFieldFocusGained

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed

        okButtonActionPerformed(evt);

    }//GEN-LAST:event_nombreFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed

        okButtonActionPerformed(evt);

    }//GEN-LAST:event_emailFieldActionPerformed

    private void telFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telFieldActionPerformed

        okButtonActionPerformed(evt);

    }//GEN-LAST:event_telFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JCheckBox favCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField telField;
    // End of variables declaration//GEN-END:variables

    private void cleanFields() {
        nombreField.setText("");
        telField.setText("");
        emailField.setText("");
    }

    private void verificarFields() {

        if (nombreField.getForeground().equals(Color.LIGHT_GRAY)) {
            nombreField.setText("");
        }
        if (emailField.getForeground().equals(Color.LIGHT_GRAY)) {
            emailField.setText("");
        }
        if (telField.getForeground().equals(Color.LIGHT_GRAY)) {
            telField.setText("");
        }
    }

}
